module.exports = [
  { text: "Мне легче заряжаться энергией в компании людей, чем в одиночестве.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "Я часто первым начинаю разговор, даже если никого почти не знаю.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "Мне нравится обсуждать идеи вслух, а не держать их только в голове.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "Активные встречи и шумные компании обычно меня оживляют.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "Если день проходит без общения, я чувствую нехватку энергии.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "В группе я обычно говорю больше, чем слушаю.", scaleType: "EI", directSide: "E", modeMin: "quick" },
  { text: "Я предпочитаю сначала обдумать всё в одиночестве, а потом делиться идеями.", scaleType: "EI", directSide: "I", modeMin: "medium" },
  { text: "После долгого общения мне часто нужно побыть одному, чтобы восстановиться.", scaleType: "EI", directSide: "I", modeMin: "medium" },
  { text: "Я чаще наблюдаю, чем активно веду разговор.", scaleType: "EI", directSide: "I", modeMin: "medium" },
  { text: "Мне комфортнее выражать мысли письменно, чем сразу говорить вслух.", scaleType: "EI", directSide: "I", modeMin: "medium" },
  { text: "В незнакомой компании я сначала присматриваюсь, а не врываюсь в центр внимания.", scaleType: "EI", directSide: "I", modeMin: "full" },
  { text: "Один спокойный вечер дома радует меня больше, чем спонтанная вечеринка.", scaleType: "EI", directSide: "I", modeMin: "full" },
  { text: "Я могу долго работать без внешней стимуляции и не скучать.", scaleType: "EI", directSide: "I", modeMin: "full" },
  { text: "Мне не нужно много общения, чтобы чувствовать, что день удался.", scaleType: "EI", directSide: "I", modeMin: "full" },
  { text: "Я раскрываюсь глубже в узком кругу, чем в большой шумной группе.", scaleType: "EI", directSide: "I", modeMin: "full" },

  { text: "Меня сильнее вдохновляют необычные идеи, чем проверенные факты.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Я часто думаю о том, что может быть, а не только о том, что уже есть.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Мне интереснее искать скрытые смыслы, чем фокусироваться на буквальных деталях.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Я люблю представлять будущее и альтернативные сценарии.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Я быстрее замечаю общую картину, чем отдельные мелочи.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Мне комфортно доверять интуиции, даже если данных пока не хватает.", scaleType: "NS", directSide: "N", modeMin: "quick" },
  { text: "Я чаще опираюсь на конкретный опыт, чем на догадки и абстракции.", scaleType: "NS", directSide: "S", modeMin: "medium" },
  { text: "Мне проще замечать факты и детали, чем улавливать скрытые намеки.", scaleType: "NS", directSide: "S", modeMin: "medium" },
  { text: "Я ценю практичные решения больше, чем красивые теории.", scaleType: "NS", directSide: "S", modeMin: "medium" },
  { text: "В новых задачах я предпочитаю сначала разобраться в реальных вводных.", scaleType: "NS", directSide: "S", modeMin: "medium" },
  { text: "Я лучше запоминаю то, что можно увидеть, потрогать или повторить на практике.", scaleType: "NS", directSide: "S", modeMin: "full" },
  { text: "Чёткие инструкции помогают мне больше, чем свободная интерпретация.", scaleType: "NS", directSide: "S", modeMin: "full" },
  { text: "Я люблю, когда идеи можно быстро приземлить на понятный результат.", scaleType: "NS", directSide: "S", modeMin: "full" },
  { text: "В разговоре я чаще спрашиваю про факты, чем про символы и подтексты.", scaleType: "NS", directSide: "S", modeMin: "full" },
  { text: "Мне проще доверять тому, что уже доказало свою полезность.", scaleType: "NS", directSide: "S", modeMin: "full" },

  { text: "При принятии решений я чаще ставлю логику выше эмоций.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "Даже в сложном разговоре мне важно, чтобы вывод оставался объективным.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "Я могу спокойно критиковать идею, если она не работает.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "В напряженной ситуации я сначала анализирую, а потом сопереживаю.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "Для меня честность обычно важнее мягкости формулировки.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "Я предпочитаю справедливые правила индивидуальным исключениям.", scaleType: "TF", directSide: "T", modeMin: "quick" },
  { text: "Мне важно, чтобы решение учитывало чувства всех участников.", scaleType: "TF", directSide: "F", modeMin: "medium" },
  { text: "Даже если логика на моей стороне, я не хочу ранить человека лишней резкостью.", scaleType: "TF", directSide: "F", modeMin: "medium" },
  { text: "Я чаще думаю о том, как решение скажется на отношениях, чем о его холодной эффективности.", scaleType: "TF", directSide: "F", modeMin: "medium" },
  { text: "В команде мне важно, чтобы атмосфера оставалась человечной и тёплой.", scaleType: "TF", directSide: "F", modeMin: "medium" },
  { text: "Я интуитивно чувствую настроение других и подстраиваю тон общения.", scaleType: "TF", directSide: "F", modeMin: "full" },
  { text: "Иногда поддержка человека важнее, чем идеальное решение задачи.", scaleType: "TF", directSide: "F", modeMin: "full" },
  { text: "Мне трудно принять выбор, который выглядит рационально, но кажется бессердечным.", scaleType: "TF", directSide: "F", modeMin: "full" },
  { text: "Я предпочитаю мягко вести людей к выводу, а не просто выдавать вердикт.", scaleType: "TF", directSide: "F", modeMin: "full" },
  { text: "Личная лояльность для меня иногда важнее формальной беспристрастности.", scaleType: "TF", directSide: "F", modeMin: "full" },

  { text: "Мне нравится, когда планы понятны заранее и все разложено по полочкам.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Я чувствую себя лучше, когда задачи закрываются до дедлайна.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Мне проще отдыхать, когда все важное уже организовано.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Я люблю списки, расписания и ощущение контроля над временем.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Неожиданные изменения планов обычно меня раздражают.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Я предпочитаю принять решение и двигаться дальше, а не держать варианты открытыми.", scaleType: "JP", directSide: "J", modeMin: "quick" },
  { text: "Мне нравится оставлять место для импровизации даже в важных делах.", scaleType: "JP", directSide: "P", modeMin: "medium" },
  { text: "Я часто чувствую себя лучше, когда не фиксирую всё слишком рано.", scaleType: "JP", directSide: "P", modeMin: "medium" },
  { text: "Спонтанность иногда делает день интереснее, чем идеальный план.", scaleType: "JP", directSide: "P", modeMin: "medium" },
  { text: "Мне проще адаптироваться на ходу, чем следовать жёсткому сценарию.", scaleType: "JP", directSide: "P", modeMin: "medium" },
  { text: "Я люблю исследовать варианты до последнего, прежде чем принять окончательное решение.", scaleType: "JP", directSide: "P", modeMin: "full" },
  { text: "Слишком жёсткие дедлайны быстро убивают у меня вдохновение.", scaleType: "JP", directSide: "P", modeMin: "full" },
  { text: "Мне нравится, когда у плана есть пространство для неожиданно хороших поворотов.", scaleType: "JP", directSide: "P", modeMin: "full" },
  { text: "Я не люблю чувствовать, что день расписан настолько плотно, что в нём нет воздуха.", scaleType: "JP", directSide: "P", modeMin: "full" },
  { text: "Иногда лучший ход для меня — сначала попробовать, а уже потом структурировать.", scaleType: "JP", directSide: "P", modeMin: "full" }
];
