window.APP_CHARACTER_DATA = (() => {
  function assetUrls(name) {
    const short = name
      .split(" ")
      .slice(0, 2)
      .map((part) => part[0])
      .join("")
      .toUpperCase();
    const encodedName = encodeURIComponent(name);

    return {
      iconUrl: `https://placehold.co/96x96/18233f/eef3ff?text=${short}`,
      imageUrl: `https://placehold.co/720x880/0e162d/f4f7ff?text=${encodedName}%0AAnime+MBTI`
    };
  }

  const typeDetails = {
    INTJ: { name: "Архитектор", description: "Стратегичный и независимый тип, который любит видеть систему целиком и действовать на несколько ходов вперед." },
    INTP: { name: "Логик", description: "Любознательный аналитик, которому важно докопаться до сути и построить красивую внутреннюю модель мира." },
    ENTJ: { name: "Командир", description: "Решительный лидер, который умеет собирать хаос в понятный план и вести остальных к результату." },
    ENTP: { name: "Полемист", description: "Быстрый, остроумный и экспериментирующий тип, которому нравится видеть возможности там, где другие видят ограничения." },
    INFJ: { name: "Советник", description: "Глубокий и интуитивный тип, который хорошо чувствует людей и ищет смысл даже в сложных ситуациях." },
    INFP: { name: "Посредник", description: "Мягкий идеалист, который держится за внутренние ценности и стремится быть искренним с собой и миром." },
    ENFJ: { name: "Наставник", description: "Теплый и вдохновляющий тип, который умеет поддерживать людей и объединять их вокруг общей идеи." },
    ENFP: { name: "Борец", description: "Энергичный и воодушевляющий тип, который заражает других энтузиазмом и любит движение вперед." },
    ISTJ: { name: "Инспектор", description: "Надежный и последовательный тип, который ценит структуру, ответственность и выполненные обещания." },
    ISFJ: { name: "Защитник", description: "Заботливый и устойчивый тип, который тонко замечает потребности других и любит приносить реальную пользу." },
    ESTJ: { name: "Администратор", description: "Организованный и прямой тип, который уважает порядок, темп и понятные правила игры." },
    ESFJ: { name: "Консул", description: "Социальный и внимательный тип, который стремится поддерживать гармонию и создавать комфорт вокруг." },
    ISTP: { name: "Мастер", description: "Практичный и собранный тип, который предпочитает действовать точно, спокойно и без лишнего шума." },
    ISFP: { name: "Артист", description: "Чуткий и свободолюбивый тип, который выражает себя через стиль, атмосферу и внутреннюю искренность." },
    ESTP: { name: "Делец", description: "Импульсивный и смелый тип, который обожает драйв, быстрое принятие решений и живое взаимодействие с миром." },
    ESFP: { name: "Исполнитель", description: "Яркий и эмоциональный тип, который любит быть в моменте, делиться эмоциями и оживлять пространство вокруг." }
  };

  const groups = {
    INTJ: { main: { name: "Lelouch Lamperouge", anime: "Code Geass", description: "Холодный стратег с длинным горизонтом мышления.", traits: ["Стратегия", "Амбиция", "Контроль"] }, others: [{ name: "Light Yagami", anime: "Death Note", description: "Рациональный и расчетливый интеллектуал.", traits: ["Аналитика", "Воля", "Системность"] }, { name: "Kurisu Makise", anime: "Steins;Gate", description: "Умная и собранная исследовательница.", traits: ["Логика", "Сдержанность", "Глубина"] }, { name: "Senku Ishigami", anime: "Dr. Stone", description: "Гениальный тактик будущего.", traits: ["Интеллект", "Изобретательность", "Фокус"] }] },
    INTP: { main: { name: "L Lawliet", anime: "Death Note", description: "Экстраординарный наблюдатель, которому важнее докопаться до истины.", traits: ["Аналитика", "Любопытство", "Нестандартность"] }, others: [{ name: "Maomao", anime: "The Apothecary Diaries", description: "Исследовательница с сильной внутренней логикой.", traits: ["Наблюдательность", "Разбор", "Ирония"] }, { name: "Armin Arlert", anime: "Attack on Titan", description: "Интеллектуал, который видит путь вперед.", traits: ["Стратегия", "Идеи", "Гибкость"] }, { name: "Shikamaru Nara", anime: "Naruto", description: "Точный мыслитель с холодной головой.", traits: ["Логика", "Спокойствие", "Предвидение"] }] },
    ENTJ: { main: { name: "Erwin Smith", anime: "Attack on Titan", description: "Харизматичный лидер, превращающий хаос в курс действий.", traits: ["Лидерство", "Решительность", "Масштаб"] }, others: [{ name: "Satsuki Kiryuin", anime: "Kill la Kill", description: "Жесткий лидер с железной дисциплиной.", traits: ["Власть", "Дисциплина", "Воля"] }, { name: "Roy Mustang", anime: "Fullmetal Alchemist", description: "Амбициозный командир с ясной целью.", traits: ["Тактика", "Харизма", "Контроль"] }, { name: "Kaguya Shinomiya", anime: "Kaguya-sama: Love Is War", description: "Сильный стратег с самоконтролем.", traits: ["Стратегия", "Холодный ум", "Амбиция"] }] },
    ENTP: { main: { name: "Gojo Satoru", anime: "Jujutsu Kaisen", description: "Яркий и блестящий импровизатор с невероятной уверенностью.", traits: ["Остроумие", "Харизма", "Импровизация"] }, others: [{ name: "Hisoka", anime: "Hunter x Hunter", description: "Хаотичный и провокационный игрок.", traits: ["Игра", "Непредсказуемость", "Драйв"] }, { name: "Oikawa Tooru", anime: "Haikyuu!!", description: "Харизматичный соревновательный ум.", traits: ["Обаяние", "Смекалка", "Амбиция"] }, { name: "Kaito Kid", anime: "Magic Kaito 1412", description: "Трюкач с любовью к эффектным решениям.", traits: ["Шарм", "Изобретательность", "Игра"] }] },
    INFJ: { main: { name: "Itachi Uchiha", anime: "Naruto", description: "Молчаливый идеалист с тяжелым чувством ответственности.", traits: ["Глубина", "Интуиция", "Самопожертвование"] }, others: [{ name: "Suguru Geto", anime: "Jujutsu Kaisen", description: "Идеолог с мощной внутренней картиной мира.", traits: ["Видение", "Убеждения", "Харизма"] }, { name: "Chrollo Lucilfer", anime: "Hunter x Hunter", description: "Тихий лидер с гипнотической глубиной.", traits: ["Спокойствие", "Смысл", "Контроль"] }, { name: "Riza Hawkeye", anime: "Fullmetal Alchemist", description: "Очень собранная защитница.", traits: ["Лояльность", "Сдержанность", "Точность"] }] },
    INFP: { main: { name: "Ken Kaneki", anime: "Tokyo Ghoul", description: "Рефлексирующий идеалист, ищущий свою правду.", traits: ["Чувствительность", "Самопоиск", "Глубина"] }, others: [{ name: "Yuta Okkotsu", anime: "Jujutsu Kaisen", description: "Тихий герой с мягким сердцем.", traits: ["Эмпатия", "Сила", "Искренность"] }, { name: "Shinji Ikari", anime: "Neon Genesis Evangelion", description: "Сложный и ранимый персонаж.", traits: ["Уязвимость", "Рефлексия", "Чувства"] }, { name: "Izuku Midoriya", anime: "My Hero Academia", description: "Идеалист, не теряющий веру в добро.", traits: ["Сострадание", "Рост", "Настойчивость"] }] },
    ENFJ: { main: { name: "Tanjiro Kamado", anime: "Demon Slayer", description: "Сильный эмпат, который ведет людей вперед сердцем.", traits: ["Тепло", "Лидерство", "Сострадание"] }, others: [{ name: "All Might", anime: "My Hero Academia", description: "Вдохновляющий символ надежды.", traits: ["Воодушевление", "Мужество", "Забота"] }, { name: "Maes Hughes", anime: "Fullmetal Alchemist", description: "Теплый человек, который делает пространство живым.", traits: ["Доброта", "Поддержка", "Открытость"] }, { name: "Tohru Honda", anime: "Fruits Basket", description: "Мягкая объединяющая сила.", traits: ["Эмпатия", "Терпение", "Свет"] }] },
    ENFP: { main: { name: "Naruto Uzumaki", anime: "Naruto", description: "Неугомонный источник энергии и веры в людей.", traits: ["Энергия", "Оптимизм", "Вдохновение"] }, others: [{ name: "Natsu Dragneel", anime: "Fairy Tail", description: "Взрывной и очень живой герой.", traits: ["Драйв", "Лояльность", "Огонь"] }, { name: "Atsushi Nakajima", anime: "Bungo Stray Dogs", description: "Сердечный и растущий герой.", traits: ["Чуткость", "Рост", "Воодушевление"] }, { name: "Anya Forger", anime: "Spy x Family", description: "Обаятельный источник эмоций.", traits: ["Веселье", "Импульс", "Обаяние"] }] },
    ISTJ: { main: { name: "Kento Nanami", anime: "Jujutsu Kaisen", description: "Надежный профессионал с сильным чувством долга.", traits: ["Надежность", "Структура", "Ответственность"] }, others: [{ name: "Levi Ackerman", anime: "Attack on Titan", description: "Точный и дисциплинированный исполнитель.", traits: ["Контроль", "Собранность", "Долг"] }, { name: "Giyu Tomioka", anime: "Demon Slayer", description: "Сдержанный защитник.", traits: ["Спокойствие", "Честь", "Выдержка"] }, { name: "Tenya Iida", anime: "My Hero Academia", description: "Организованный лидер порядка.", traits: ["Порядок", "Ответственность", "Дисциплина"] }] },
    ISFJ: { main: { name: "Hinata Hyuga", anime: "Naruto", description: "Тихая и очень преданная героиня, растущая через внутреннюю силу.", traits: ["Преданность", "Мягкость", "Рост"] }, others: [{ name: "Ochaco Uraraka", anime: "My Hero Academia", description: "Добрая и практичная поддержка.", traits: ["Забота", "Тепло", "Искренность"] }, { name: "Chise Hatori", anime: "The Ancient Magus' Bride", description: "Чуткая героиня с глубоким внутренним миром.", traits: ["Чувствительность", "Терпение", "Нежность"] }, { name: "Yor Forger", anime: "Spy x Family", description: "Заботливая защитница с тихой преданностью.", traits: ["Защита", "Лояльность", "Тепло"] }] },
    ESTJ: { main: { name: "Tenya Iida", anime: "My Hero Academia", description: "Организованный и очень надежный лидер, уважающий порядок.", traits: ["Порядок", "Темп", "Ответственность"] }, others: [{ name: "Vegeta", anime: "Dragon Ball", description: "Жесткий и целеустремленный боец.", traits: ["Сила", "Гордость", "Результат"] }, { name: "Olivier Armstrong", anime: "Fullmetal Alchemist", description: "Жесткий управленец без романтики.", traits: ["Контроль", "Суровость", "Дисциплина"] }, { name: "Nobara Kugisaki", anime: "Jujutsu Kaisen", description: "Уверенная и решительная героиня.", traits: ["Прямота", "Сила", "Самоуважение"] }] },
    ESFJ: { main: { name: "Momo Yaoyorozu", anime: "My Hero Academia", description: "Заботливая организаторша, которая старается быть полезной людям.", traits: ["Поддержка", "Организация", "Забота"] }, others: [{ name: "Winry Rockbell", anime: "Fullmetal Alchemist", description: "Практичная и очень теплая опора.", traits: ["Забота", "Практичность", "Лояльность"] }, { name: "Kobeni Higashiyama", anime: "Chainsaw Man", description: "Социально настроенная героиня с сильными чувствами.", traits: ["Чувства", "Люди", "Реактивность"] }, { name: "Orihime Inoue", anime: "Bleach", description: "Светлая и сердечная поддержка.", traits: ["Доброта", "Нежность", "Оптимизм"] }] },
    ISTP: { main: { name: "Levi Ackerman", anime: "Attack on Titan", description: "Минимум слов, максимум точности и эффективности.", traits: ["Точность", "Холодная голова", "Практика"] }, others: [{ name: "Roronoa Zoro", anime: "One Piece", description: "Надежный и самостоятельный боец.", traits: ["Сила", "Самостоятельность", "Фокус"] }, { name: "Toji Fushiguro", anime: "Jujutsu Kaisen", description: "Опасный прагматик, который действует быстро и четко.", traits: ["Инстинкт", "Скорость", "Практичность"] }, { name: "Mikasa Ackerman", anime: "Attack on Titan", description: "Собранная защитница с сильной концентрацией.", traits: ["Действие", "Верность", "Тишина"] }] },
    ISFP: { main: { name: "Megumi Fushiguro", anime: "Jujutsu Kaisen", description: "Сдержанный и внутренне принципиальный персонаж.", traits: ["Сдержанность", "Принципы", "Самостоятельность"] }, others: [{ name: "Bocchi Hitori", anime: "Bocchi the Rock!", description: "Искренняя героиня с ярким внутренним миром.", traits: ["Чувствительность", "Творчество", "Искренность"] }, { name: "Saber", anime: "Fate/stay night", description: "Благородная и сдержанная воительница.", traits: ["Честь", "Грация", "Выдержка"] }, { name: "Kenshin Himura", anime: "Rurouni Kenshin", description: "Спокойный защитник с сильным моральным кодексом.", traits: ["Мир", "Принципы", "Сдержанность"] }] },
    ESTP: { main: { name: "Joseph Joestar", anime: "JoJo's Bizarre Adventure", description: "Дерзкий и очень живой герой, который обожает риск и игру.", traits: ["Смелость", "Импровизация", "Драйв"] }, others: [{ name: "Yusuke Urameshi", anime: "Yu Yu Hakusho", description: "Прямой и резкий герой действия.", traits: ["Энергия", "Смелость", "Напор"] }, { name: "Inosuke Hashibira", anime: "Demon Slayer", description: "Инстинктивный и хаотичный боец.", traits: ["Импульс", "Сила", "Свобода"] }, { name: "Reigen Arataka", anime: "Mob Psycho 100", description: "Обаятельный импровизатор с молниеносной реакцией.", traits: ["Шарм", "Гибкость", "Быстрый ум"] }] },
    ESFP: { main: { name: "Ryuko Matoi", anime: "Kill la Kill", description: "Яркая и эмоциональная героиня, которая не боится быть собой.", traits: ["Эмоции", "Храбрость", "Яркость"] }, others: [{ name: "Power", anime: "Chainsaw Man", description: "Хаотичная и очень эффектная энергия.", traits: ["Хаос", "Эмоции", "Сцена"] }, { name: "Denji", anime: "Chainsaw Man", description: "Прямолинейный герой момента.", traits: ["Жизнелюбие", "Импульс", "Простота"] }, { name: "Nami", anime: "One Piece", description: "Яркая и живая героиня с сильным чувством момента.", traits: ["Обаяние", "Гибкость", "Энергия"] }] }
  };

  Object.values(groups).forEach((group) => {
    group.main = { ...group.main, ...assetUrls(group.main.name) };
    group.others = group.others.map((character) => ({ ...character, ...assetUrls(character.name) }));
  });

  return {
    typeDetails,
    groups
  };
})();
